# This file is generated by CMake Tools! DO NOT EDIT!
cmake_policy(PUSH)
if(POLICY CMP0053)
   cmake_policy(SET CMP0053 NEW)
endif()
set(BUILD_SHARED_LIBS "TRUE" CACHE BOOL "Variable supplied by CMakeTools. Value is forced." FORCE)
set(CMAKE_EXPORT_COMPILE_COMMANDS "TRUE" CACHE BOOL "Variable supplied by CMakeTools. Value is forced." FORCE)
set(CMAKE_MODULE_PATH "c:/users/andre/onedrive - blackburn college/year 3 project/project/real-time-rendering/cmakeBuilds/CMakeTools" CACHE STRING "Variable supplied by CMakeTools. Value is forced." FORCE)
cmake_policy(POP)